version: 2
jobs:
  backend:
    docker:
      - image: circleci/node:8.12
      - image: circleci/mongo:3.6.3

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Backend Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Backend Linter
          command: ./node_modules/.bin/eslint src

      - run:
          name: Running Backend Testing
          command: npm test

  frontend:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/project

    steps:
      - checkout
      
      -run 
        name: Change Directory
        command: cd client

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Frontend Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     name: Running Frontend Linter
      #     command: ./node_modules/.bin/eslint src

      - run:
          name: Running Frontend Build
          command: npm run build

workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend
      - frontend
