version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
      - image: circleci/mongo:3.6.3

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Backend Linter
          command: ./node_modules/.bin/eslint src

      - run:
          name: npm test
          command: npm test
