version: 2
jobs:
  build_backend:
    docker:
      - image: circleci/node:8.12
      - image: circleci/mongo:3.6.3

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}s
            - v1-dependencies-

      - run:
        name: Install Dependencies
        command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Backend Linter
          command: ./node_modules/.bin/eslint src

      - run:
          name: npm test
          command: ./node_modules/.bin/nyc ./node_modules/.bin/mocha --recursive --timeout=20000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
          when: always
#   build:
#     docker:
#       - image: circleci/node:8.12
#     working_directory: ~~/repo/client
#      steps:
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}s
#             - v1-dependencies-
#       - run: npm install
#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}
#       - run: npm run build
# workflows:
#   test_and_build:
#     - test
#     - build:
#         requires: -test
